### PR TITLE
ci: standardise workflows using SciML's reusable workflows

### PR DESCRIPTION
**Pull request by thazhemadam**
Update the workflows in this repository to use SciML's reusable workflows.
This is part of a larger effort to standardise the SciML's CI workflows for more generic and common requirements, to keep the workflows uniform and easier to maintain.

### CODE REVIEW

**Comment by gdalle** [comment]
Where does this build the docs? And are they updated directly upon each merged PR?

**Comment by thazhemadam** [comment]
The documentation is still built on the same events as it is at present, i.e., on pushes to `main`, on all tags pushed and on all pull requests opened. The status quo is expected to remain unchanged. https://github.com/SciML/ADTypes.jl/blob/0f86da069c526ad1b785aca415026e1610c534ff/.github/workflows/Documentation.yml#L3-L8

**Comment by gdalle** [comment]
I mean on which website, does it go to a centralized SciML docs or does it stay here?

**Comment by thazhemadam** [comment]
Ah, I see. Sorry about the misunderstanding. The documentation deployments will continue to stay here, as specified in the `deploydocs` method.
https://github.com/SciML/ADTypes.jl/blob/a67c600dacccdf1c55b9e975bdc0b4621fec2dd4/docs/make.jl#L11

**Comment by Vaibhavdixit02** [comment]
Even though it passed tests in the PR the CI on master seems to have broken can you take a look @thazhemadam?

**Comment by gdalle** [comment]
I re-ran the failed workflows and it worked, I think it was just a Codecov glitch

**Pull request merged**
